version: '3'


services: 

  # application:
  #   image: "mentorhub-app"
  #   build: "./mentorhub-app"
  #   container_name: "application"
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - "mongo"
  #     - "elasticsearch"
  #     - "monstache"
  #     - "mailhog"
  #   networks:
  #     - "mentorhub_network"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: "mailhog"
    ports:
      - "1025:1025"
      - "8025:8025"
    expose:
      - "1025"
    networks:
      - "mentorhub_network"

  mongo:
    image: mongo:5.0.2
    container_name: "mongodb"
    ports: 
     - "27017:27017"
    expose:
     - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs0", "--bind_ip_all"]
    networks: 
      - "mentorhub_network"

  elasticsearch:
    image: elasticsearch:7.14.0
    container_name: "elasticsearchdb"
    ports: 
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200"
      - "9300"
    networks:
      - "mentorhub_network"
    environment: 
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  monstache:
    image: rwynn/monstache:latest
    container_name: "monstache"
    restart: unless-stopped
    entrypoint: monstache -mongo-url='mongodb://mongo:27017' -elasticsearch-url='http://elasticsearch:9200/' -direct-read-namespace='mentorhub.mentorshipRequest' -change-stream-namespace='mentorhub.mentorshipRequest'
    depends_on:
      - "mongo"
      - "elasticsearch"
    networks: 
      - "mentorhub_network"

  mongosetup:
    image: "mongo-setup"
    build: "./mongo-setup"
    container_name: "mongosetup"
    depends_on:
      - "mongo"
    networks:
      - "mentorhub_network"


networks: 
  mentorhub_network: