spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 202364333101-h14l0ahfcok5kf658ddknptji32gicnb.apps.googleusercontent.com
            clientSecret: 0G2uxVRFTA4thxzS1DeBPCV7
  ldap:
    embedded:
      ldif: classpath:ldap-data.ldif
      base-dn: dc=springframework,dc=org
      port: 8389
  data:
    mongodb:
      host: mongo
      port: 27017
      database: mentorhub
    elasticsearch:
      repositories:
        enabled: false
logging:
  pattern.dateformat: yyyy-MM-dd HH:mm:ss.SSS,Europe/Istanbul
  level:
    root: INFO
    org.springframework.data.convert.CustomConversions: ERROR